name: Bonjour
on:
  - push
jobs:
  run-maven:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - run: mvn -version
      - run: help:effective-pom

  dire_bonjour:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest # image de docker
      options: --user=root #runner comme root
    steps:
      - uses: actions/checkout@v2 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run: |
          sudo apt-get update
          sudo apt-get install -y cowsay
      - run: cat README.md | cowsay